import { Router, type Request, type Response, type NextFunction } from "express";
import { and, asc, count, eq } from "drizzle-orm";
import { db, sessionsTable, agentsTable, approvalsTable } from "@workspace/db";

const router = Router();

function authenticatedUserId(req: Request): number | null {
  return typeof req.session?.userId === "number" && req.session.userId > 0
    ? req.session.userId
    : null;
}

function parsePositiveId(value: unknown): number | null {
  const parsed = Number.parseInt(String(value ?? ""), 10);
  return Number.isInteger(parsed) && parsed > 0 ? parsed : null;
}

/**
 * Return only the authenticated user's sessions. Legacy rows with no owner are
 * intentionally not exposed through normal user APIs; they require an explicit
 * administrative migration before use.
 */
router.get("/sessions", async (req, res, next): Promise<void> => {
  const userId = authenticatedUserId(req);
  if (!userId) {
    res.status(401).json({ error: "Authentication required" });
    return;
  }

  try {
    const rawLimit = Number.parseInt(String(req.query.limit ?? "100"), 10);
    const rawOffset = Number.parseInt(String(req.query.offset ?? "0"), 10);
    const limit = Math.min(Number.isNaN(rawLimit) ? 100 : Math.max(1, rawLimit), 500);
    const offset = Number.isNaN(rawOffset) ? 0 : Math.max(0, rawOffset);

    const [sessions, totalRows] = await Promise.all([
      db
        .select()
        .from(sessionsTable)
        .where(eq(sessionsTable.userId, userId))
        .orderBy(asc(sessionsTable.id))
        .limit(limit)
        .offset(offset),
      db
        .select({ total: count() })
        .from(sessionsTable)
        .where(eq(sessionsTable.userId, userId)),
    ]);

    const sessionIds = sessions.map((session) => session.id);
    const agents = sessionIds.length === 0
      ? []
      : await db
          .select()
          .from(agentsTable)
          .where(
            // Avoid importing inArray for a single purpose while retaining a
            // parameterised query generated by Drizzle.
            sessionIds.length === 1
              ? eq(agentsTable.sessionId, sessionIds[0]!)
              : undefined,
          );

    // For more than one session, issue one bounded query per returned session.
    // This boundary is security-critical and favours explicit ownership over
    // inheriting the legacy unscoped list implementation.
    const agentsBySession = new Map<number, typeof agents>();
    if (sessionIds.length === 1) {
      agentsBySession.set(sessionIds[0]!, agents);
    } else {
      await Promise.all(sessionIds.map(async (sessionId) => {
        const rows = await db.select().from(agentsTable).where(eq(agentsTable.sessionId, sessionId));
        agentsBySession.set(sessionId, rows);
      }));
    }

    res.json(sessions.map((session) => ({
      ...session,
      agentModes: (agentsBySession.get(session.id) ?? []).map((agent) => ({
        name: agent.name,
        provider: agent.provider,
        isMock: agent.isMock,
      })),
    })));
    void totalRows;
  } catch (err) {
    next(err);
  }
});

/**
 * Production sessions must use real provider adapters. Simulation is available
 * only in tests or when an operator explicitly enables ALLOW_SIMULATION_MODE.
 */
router.post("/sessions", (req, res, next): void => {
  const allowSimulation = process.env.NODE_ENV === "test" || process.env.ALLOW_SIMULATION_MODE === "true";
  const agents = Array.isArray(req.body?.agents) ? req.body.agents as Array<Record<string, unknown>> : [];
  const containsMock = agents.some((agent) => agent.isMock === true);

  if (containsMock && !allowSimulation) {
    res.status(422).json({
      error: "simulation_disabled",
      message: "VIBA production sessions require configured live AI providers. Simulation agents are disabled.",
    });
    return;
  }

  next();
});

/**
 * Every nested session route is owner-scoped before the legacy route handler
 * can read or mutate related agents, tasks, messages, approvals, memory, logs,
 * exports, or SSE snapshots.
 */
router.use("/sessions/:id", async (req, res, next): Promise<void> => {
  const userId = authenticatedUserId(req);
  const sessionId = parsePositiveId(req.params.id);

  if (!userId) {
    res.status(401).json({ error: "Authentication required" });
    return;
  }
  if (!sessionId) {
    res.status(400).json({ error: "Invalid session id" });
    return;
  }

  try {
    const [owned] = await db
      .select({ id: sessionsTable.id })
      .from(sessionsTable)
      .where(and(eq(sessionsTable.id, sessionId), eq(sessionsTable.userId, userId)))
      .limit(1);

    if (!owned) {
      // Return 404 rather than 403 so session identifiers are not disclosed.
      res.status(404).json({ error: "Session not found" });
      return;
    }

    if (req.method === "POST" && req.path === "/approve") {
      const approvalId = parsePositiveId(req.body?.approvalId);
      if (!approvalId) {
        res.status(400).json({ error: "Invalid approval id" });
        return;
      }
      const [approval] = await db
        .select({ id: approvalsTable.id })
        .from(approvalsTable)
        .where(and(eq(approvalsTable.id, approvalId), eq(approvalsTable.sessionId, sessionId)))
        .limit(1);
      if (!approval) {
        res.status(404).json({ error: "Approval not found" });
        return;
      }
    }

    next();
  } catch (err) {
    next(err);
  }
});

export default router;
