import type { ToolDefinition } from "./toolRegistry";

/** Safe defensive security review tools exposed through the VIBA Tool Action Broker. */
export const SECURITY_HARDENING_TOOLS: ToolDefinition[] = [
  {
    toolId: "security.auth_idor.audit",
    label: "Security: Auth and Ownership Review",
    category: "security",
    description: "Review authentication, session ownership, route guards, and object-level access checks. Report-only; no external probing and no mutation.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.session_csrf.audit",
    label: "Security: Session and Cookie Review",
    category: "security",
    description: "Review session fixation controls, cookie flags, OAuth state validation, CSRF-sensitive paths, and login rate limits.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.data_handling.audit",
    label: "Security: Data Handling Review",
    category: "security",
    description: "Review data retention, deletion, export, audit logging, credential storage, and redaction controls.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.config.review",
    label: "Security: Config and Headers Review",
    category: "security",
    description: "Review security headers, CORS allow-lists, iframe policy, environment requirements, and safe deployment defaults.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.dependency.review",
    label: "Security: Dependency Review",
    category: "security",
    description: "Review dependency policy, package manager settings, build scripts, and supply-chain hardening status.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.guard_patch.plan",
    label: "Security: Guard Patch Plan",
    category: "security",
    description: "Prepare a non-mutating patch plan for missing authentication, ownership, admin, redaction, or policy guards.",
    riskLevel: "low",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.access_test.plan",
    label: "Security: Access Test Plan",
    category: "security",
    description: "Prepare regression tests for 401/403 access checks, owner-only changes, admin-only routes, and embed boundary cases.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.safe_patch.apply",
    label: "Security: Apply Approved Patch",
    category: "security",
    description: "Apply a defensive security patch only after owner approval and passing the safe-build gate.",
    riskLevel: "high",
    permissionsRequired: ["login_required", "owner_approval_required", "dry_run_required", "safe_build_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },
];

export function getSecurityHardeningToolById(toolId: string): ToolDefinition | undefined {
  return SECURITY_HARDENING_TOOLS.find((tool) => tool.toolId === toolId);
}
