import type { ToolDefinition } from "./toolRegistry";

/** Safe defensive website testing and security review tools exposed through the VIBA Tool Action Broker. */
export const SECURITY_HARDENING_TOOLS: ToolDefinition[] = [
  // ─── Core security review ────────────────────────────────────────────────────
  {
    toolId: "security.auth_idor.audit",
    label: "Security: Auth and Ownership Review",
    category: "security",
    description: "Review authentication, session ownership, route guards, and object-level access checks. Report-only; no external probing and no mutation.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.session_csrf.audit",
    label: "Security: Session and Cookie Review",
    category: "security",
    description: "Review session fixation controls, cookie flags, OAuth state validation, CSRF-sensitive paths, and login rate limits.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.data_handling.audit",
    label: "Security: Data Handling Review",
    category: "security",
    description: "Review data retention, deletion, export, audit logging, credential storage, and redaction controls.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.config.review",
    label: "Security: Config and Headers Review",
    category: "security",
    description: "Review security headers, CORS allow-lists, iframe policy, environment requirements, and safe deployment defaults.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.dependency.review",
    label: "Security: Dependency Review",
    category: "security",
    description: "Review dependency policy, package manager settings, build scripts, and supply-chain hardening status.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  // ─── Website functional and UI QA ───────────────────────────────────────────
  {
    toolId: "website.crawl.map",
    label: "Website: Crawl and Page Map",
    category: "browser",
    description: "Build a same-origin page map from navigation, sitemap links, and discovered internal links. Read-only crawler for owner-approved targets.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "website.link_check",
    label: "Website: Broken Link Check",
    category: "browser",
    description: "Check internal links, anchors, redirects, 404/5xx responses, and broken asset references. Read-only and rate-limited.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "website.ui_smoke_test",
    label: "Website: UI Smoke Test",
    category: "browser",
    description: "Open key pages and verify visible buttons, links, menus, modals, forms, loading states, console errors, and obvious rendering failures.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "website.form_flow_test",
    label: "Website: Form Flow Test",
    category: "browser",
    description: "Test forms using safe dummy data only. Blocks payment, destructive, account-changing, or production-submission steps unless explicitly approved.",
    riskLevel: "medium",
    permissionsRequired: ["login_required", "dry_run_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "website.responsive_visual_check",
    label: "Website: Responsive Visual Check",
    category: "browser",
    description: "Check mobile, tablet, and desktop viewports for overflow, clipped content, broken navigation, hidden CTAs, and layout shifts.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "website.console_network_audit",
    label: "Website: Console and Network Audit",
    category: "browser",
    description: "Collect browser console errors, failed network requests, slow requests, mixed-content warnings, and client-side crash evidence.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "website.download_safety.review",
    label: "Website: Download Safety Review",
    category: "security",
    description: "Review downloadable files by metadata, MIME type, extension, content-disposition, and quarantine status. Does not execute downloaded files.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  // ─── Performance, accessibility, standards and SEO-quality checks ───────────
  {
    toolId: "quality.lighthouse.audit",
    label: "Quality: Lighthouse Audit",
    category: "browser",
    description: "Run Lighthouse-style page quality checks for performance, accessibility, SEO, best practices, and PWA readiness where supported.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "quality.core_web_vitals.audit",
    label: "Quality: Core Web Vitals Review",
    category: "browser",
    description: "Review LCP, CLS, INP-style interaction risk, render-blocking resources, image weight, script cost, and mobile performance blockers.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "quality.accessibility.axe_audit",
    label: "Quality: Axe Accessibility Audit",
    category: "browser",
    description: "Run axe-style accessibility checks for WCAG-related issues, ARIA misuse, labels, landmarks, headings, contrast candidates, and keyboard traps.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "quality.keyboard_navigation.audit",
    label: "Quality: Keyboard Navigation Audit",
    category: "browser",
    description: "Check tab order, focus visibility, skip links, modal focus trapping, escape behavior, and keyboard-only completion of key flows.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "quality.seo_technical.audit",
    label: "Quality: Technical SEO Audit",
    category: "browser",
    description: "Check titles, meta descriptions, canonical tags, robots directives, structured data presence, status codes, and crawlability blockers.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  // ─── Passive website security checks ────────────────────────────────────────
  {
    toolId: "security.passive_baseline.audit",
    label: "Security: Passive Baseline Audit",
    category: "security",
    description: "Run a non-invasive baseline review aligned to OWASP-style web testing categories. No exploit payloads, brute force, or stress testing.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.tls_certificate.audit",
    label: "Security: TLS and Certificate Audit",
    category: "security",
    description: "Review HTTPS redirect behavior, certificate validity, hostname coverage, expiry, protocol posture, and HSTS presence.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.http_headers.audit",
    label: "Security: HTTP Headers Audit",
    category: "security",
    description: "Review CSP, HSTS, X-Content-Type-Options, Referrer-Policy, Permissions-Policy, cache-control, and framing policy.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.cookie_flags.audit",
    label: "Security: Cookie Flags Audit",
    category: "security",
    description: "Review cookie Secure, HttpOnly, SameSite, Path, Domain, Max-Age/Expires, and cross-site credential implications.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.csp.audit",
    label: "Security: CSP Audit",
    category: "security",
    description: "Review Content-Security-Policy for unsafe-inline, unsafe-eval, broad connect-src/frame-src/img-src, frame-ancestors, and reporting gaps.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.cors.audit",
    label: "Security: CORS Audit",
    category: "security",
    description: "Review CORS allowed origins, credentials mode, wildcard combinations, preflight behavior, and environment-driven origin controls.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.redirect_mixed_content.audit",
    label: "Security: Redirect and Mixed Content Audit",
    category: "security",
    description: "Review HTTP-to-HTTPS redirects, redirect chains, open-ended redirect patterns, mixed-content warnings, and insecure asset loading.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.sensitive_data_exposure.audit",
    label: "Security: Sensitive Data Exposure Review",
    category: "security",
    description: "Review pages, responses, headers, client bundles, source maps, and logs for accidental exposure patterns. Findings are redacted.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.sitemap_robots.review",
    label: "Security: Sitemap and Robots Review",
    category: "security",
    description: "Review sitemap.xml, robots.txt, public route exposure, disallowed paths, indexing controls, and accidental admin path discovery.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  // ─── API and access-control checks ──────────────────────────────────────────
  {
    toolId: "api.contract.audit",
    label: "API: Contract and Schema Audit",
    category: "security",
    description: "Review API routes, request schemas, response shapes, error handling, body limits, and server-side validation coverage.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "api.authz_matrix.audit",
    label: "API: Authorization Matrix Audit",
    category: "security",
    description: "Check documented 401/403/200 expectations for routes using owner-approved test accounts or local test fixtures only.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "api.rate_limit.audit",
    label: "API: Rate Limit and Abuse-Control Review",
    category: "security",
    description: "Review configured rate limits, expensive endpoint throttles, auth attempt limits, notification limits, and fail-closed behavior. No load testing.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  // ─── Supply-chain and deployment security ───────────────────────────────────
  {
    toolId: "supply.sbom.generate",
    label: "Supply Chain: Generate SBOM",
    category: "build",
    description: "Generate a software bill of materials from project manifests where supported. No dependency installation or mutation.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "supply.dependency_vuln.audit",
    label: "Supply Chain: Dependency Risk Audit",
    category: "build",
    description: "Review package manifests, lockfiles, known risky dependency patterns, pinned versions, package-manager policy, and upgrade recommendations.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "supply.license.review",
    label: "Supply Chain: License Review",
    category: "build",
    description: "Review dependency license metadata and flag commercial-use, copyleft, unknown, or policy-sensitive licenses for human review.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "deployment.config_security.review",
    label: "Deployment: Config Security Review",
    category: "deployment",
    description: "Review deployment config, build/start commands, environment-variable names, public/private service boundaries, and safe rollback readiness.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  // ─── Planning, patching and reporting ───────────────────────────────────────
  {
    toolId: "security.guard_patch.plan",
    label: "Security: Guard Patch Plan",
    category: "security",
    description: "Prepare a non-mutating patch plan for missing authentication, ownership, admin, redaction, or policy guards.",
    riskLevel: "low",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.access_test.plan",
    label: "Security: Access Test Plan",
    category: "security",
    description: "Prepare regression tests for 401/403 access checks, owner-only changes, admin-only routes, and embed boundary cases.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "report.owasp_asvs.generate",
    label: "Reports: OWASP ASVS Checklist",
    category: "reports",
    description: "Generate a checklist-style report mapped to OWASP ASVS verification categories and VIBA evidence items.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "report.owasp_wstg.generate",
    label: "Reports: OWASP WSTG Checklist",
    category: "reports",
    description: "Generate a checklist-style website security testing report mapped to OWASP Web Security Testing Guide-style categories.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "report.website_qa.generate",
    label: "Reports: Website QA Report",
    category: "reports",
    description: "Generate a client-ready website QA report covering broken links, UI defects, forms, performance, accessibility, SEO, and security findings.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  {
    toolId: "security.safe_patch.apply",
    label: "Security: Apply Approved Patch",
    category: "security",
    description: "Apply a defensive security patch only after owner approval and passing the safe-build gate.",
    riskLevel: "high",
    permissionsRequired: ["login_required", "owner_approval_required", "dry_run_required", "safe_build_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },
];

export function getSecurityHardeningToolById(toolId: string): ToolDefinition | undefined {
  return SECURITY_HARDENING_TOOLS.find((tool) => tool.toolId === toolId);
}
