/**
 * VIBA Tool Registry
 *
 * Defines every tool agents can request through the Tool Action Broker.
 * No tool may claim outputsSecretValues: true.
 * Agents never call tools directly — they request through the broker.
 */

export type ToolCategory =
  | "repository"
  | "deployment"
  | "payments"
  | "dns"
  | "email"
  | "browser"
  | "build"
  | "security"
  | "vault"
  | "ai"
  | "storage"
  | "reports"
  | "network"
  | "utility"
  | "comms"
  | "data"
  | "testing"
  | "inference"
  | "devtools";

export type RiskLevel = "read_only" | "low" | "medium" | "high" | "destructive";

export type PermissionType =
  | "none"
  | "login_required"
  | "vault_required"
  | "owner_approval_required"
  | "admin_required"
  | "dry_run_required"
  | "safe_build_required";

export interface ToolDefinition {
  toolId: string;
  label: string;
  category: ToolCategory;
  description: string;
  riskLevel: RiskLevel;
  permissionsRequired: PermissionType[];
  credentialProvider: string | null;
  credentialKind: string | null;
  supportsDryRun: boolean;
  requiresApproval: boolean;
  requiresSafeBuild: boolean;
  outputsSecretValues: false;
  /**
   * Maps this broker tool to a concrete tool name in tools/registry.ts.
   * When set, executeToolAction() calls executeTool(executionName, payload, ctx)
   * for real execution instead of returning an integration stub.
   */
  executionName?: string;
}

export const TOOL_REGISTRY: Record<string, ToolDefinition> = {
  "github.repo.read": {
    toolId: "github.repo.read",
    label: "GitHub: Read Repository",
    category: "repository",
    description: "Read repository contents, files, branches, and metadata from GitHub.",
    riskLevel: "read_only",
    permissionsRequired: ["vault_required"],
    credentialProvider: "github",
    credentialKind: "token",
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "github.repo.write": {
    toolId: "github.repo.write",
    label: "GitHub: Write Repository",
    category: "repository",
    description: "Create or update files, branches, and commits in a GitHub repository.",
    riskLevel: "medium",
    permissionsRequired: ["vault_required", "dry_run_required"],
    credentialProvider: "github",
    credentialKind: "token",
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "github.pr.create": {
    toolId: "github.pr.create",
    label: "GitHub: Create Pull Request",
    category: "repository",
    description: "Open a pull request on GitHub for review.",
    riskLevel: "low",
    permissionsRequired: ["vault_required"],
    credentialProvider: "github",
    credentialKind: "token",
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "github.pr.merge": {
    toolId: "github.pr.merge",
    label: "GitHub: Merge Pull Request",
    category: "repository",
    description: "Merge an approved pull request on GitHub.",
    riskLevel: "high",
    permissionsRequired: ["vault_required", "owner_approval_required", "safe_build_required"],
    credentialProvider: "github",
    credentialKind: "token",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },
  "railway.env.read": {
    toolId: "railway.env.read",
    label: "Railway: Read Environment Variables",
    category: "deployment",
    description: "Read environment variable keys (not values) from a Railway service.",
    riskLevel: "read_only",
    permissionsRequired: ["vault_required"],
    credentialProvider: "railway",
    credentialKind: "token",
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "railway.env.write": {
    toolId: "railway.env.write",
    label: "Railway: Write Environment Variables",
    category: "deployment",
    description: "Set or update environment variables in a Railway service. Triggers redeploy.",
    riskLevel: "high",
    permissionsRequired: ["vault_required", "owner_approval_required", "dry_run_required"],
    credentialProvider: "railway",
    credentialKind: "token",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "railway.deploy.status": {
    toolId: "railway.deploy.status",
    label: "Railway: Check Deployment Status",
    category: "deployment",
    description: "Check the current status of a Railway deployment.",
    riskLevel: "read_only",
    permissionsRequired: ["vault_required"],
    credentialProvider: "railway",
    credentialKind: "token",
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "railway.deploy.trigger": {
    toolId: "railway.deploy.trigger",
    label: "Railway: Trigger Deployment",
    category: "deployment",
    description: "Trigger a Railway deployment. Requires safe build gate and user approval.",
    riskLevel: "destructive",
    permissionsRequired: ["vault_required", "owner_approval_required", "dry_run_required", "safe_build_required"],
    credentialProvider: "railway",
    credentialKind: "token",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },
  "stripe.products.read": {
    toolId: "stripe.products.read",
    label: "Stripe: Read Products & Prices",
    category: "payments",
    description: "Read product and price data from Stripe.",
    riskLevel: "read_only",
    permissionsRequired: ["vault_required"],
    credentialProvider: "stripe",
    credentialKind: "api_key",
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "stripe.products.write": {
    toolId: "stripe.products.write",
    label: "Stripe: Create/Update Products",
    category: "payments",
    description: "Create or update products and prices in Stripe.",
    riskLevel: "high",
    permissionsRequired: ["vault_required", "owner_approval_required", "dry_run_required"],
    credentialProvider: "stripe",
    credentialKind: "api_key",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "stripe.webhook.verify": {
    toolId: "stripe.webhook.verify",
    label: "Stripe: Verify Webhook",
    category: "payments",
    description: "Verify a Stripe webhook signature. Read-only validation.",
    riskLevel: "read_only",
    permissionsRequired: ["vault_required"],
    credentialProvider: "stripe",
    credentialKind: "api_key",
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "credits.ledger.read": {
    toolId: "credits.ledger.read",
    label: "Credits: Read Ledger",
    category: "payments",
    description: "Read credit balance and transaction history for a user.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "credits.ledger.write": {
    toolId: "credits.ledger.write",
    label: "Credits: Write Ledger",
    category: "payments",
    description: "Adjust credit balance. Admin only. Requires audit log.",
    riskLevel: "destructive",
    permissionsRequired: ["admin_required", "owner_approval_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "dns.records.read": {
    toolId: "dns.records.read",
    label: "DNS: Read Records",
    category: "dns",
    description: "Read DNS records for a domain.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "dns.records.write": {
    toolId: "dns.records.write",
    label: "DNS: Write Records",
    category: "dns",
    description: "Create or update DNS records. Shows exact changes before execute. Approval required.",
    riskLevel: "high",
    permissionsRequired: ["owner_approval_required", "dry_run_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "smtp.test": {
    toolId: "smtp.test",
    label: "SMTP: Send Test Email",
    category: "email",
    description: "Send a test email to verify SMTP configuration.",
    riskLevel: "low",
    permissionsRequired: ["vault_required"],
    credentialProvider: "smtp",
    credentialKind: "password",
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "browser.open": {
    toolId: "browser.open",
    label: "Browser: Open URL",
    category: "browser",
    description: "Open a URL in the supervised browser operator.",
    riskLevel: "low",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "browser.authorized_action": {
    toolId: "browser.authorized_action",
    label: "Browser: Authorized Action",
    category: "browser",
    description: "Perform a supervised browser action (form submit, OAuth flow, etc.). User authorization required. Downloads quarantined.",
    riskLevel: "high",
    permissionsRequired: ["login_required", "owner_approval_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "build.safe_build": {
    toolId: "build.safe_build",
    label: "Build: Safe Build Gate",
    category: "build",
    description: "Run pnpm run safe-build: typecheck, API tests, API build, frontend build. Must pass before deploy.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "security.business_plan": {
    toolId: "security.business_plan",
    label: "Security: Business Security Plan",
    category: "security",
    description: "Generate a tailored security hardening plan for the project.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "security.malware_plan": {
    toolId: "security.malware_plan",
    label: "Security: Malware/Build Safety",
    category: "security",
    description: "Evaluate uploaded code and build artifacts for safety issues.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "vault.credential.status": {
    toolId: "vault.credential.status",
    label: "Vault: Credential Status",
    category: "vault",
    description: "Check whether a vault credential exists (metadata only, no raw value).",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "vault.credential.use": {
    toolId: "vault.credential.use",
    label: "Vault: Use Credential (Server-Side)",
    category: "vault",
    description: "Resolve and use an encrypted credential server-side. Raw value never exposed to frontend or agents.",
    riskLevel: "medium",
    permissionsRequired: ["vault_required", "login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "ai.custom.use": {
    toolId: "ai.custom.use",
    label: "AI: Use Custom BYOK Provider",
    category: "ai",
    description: "Route a task to a user-saved custom AI provider (BYOK). Credentials resolved server-side.",
    riskLevel: "low",
    permissionsRequired: ["vault_required"],
    credentialProvider: "custom_ai",
    credentialKind: "api_key",
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "report.evidence.generate": {
    toolId: "report.evidence.generate",
    label: "Reports: Generate Evidence Report",
    category: "reports",
    description: "Generate a final evidence report for a completed task. No secrets included.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "production.target.read": {
    toolId: "production.target.read",
    label: "Production: Read Target",
    category: "deployment",
    description: "Read a production monitoring target. No mutations.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "production.target.write": {
    toolId: "production.target.write",
    label: "Production: Write Target",
    category: "deployment",
    description: "Create or update a production monitoring target configuration.",
    riskLevel: "low",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "production.check.run": {
    toolId: "production.check.run",
    label: "Production: Run Health Check",
    category: "deployment",
    description: "Run read-only health checks against a production target. No deployment mutations.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "production.incident.read": {
    toolId: "production.incident.read",
    label: "Production: Read Incident",
    category: "deployment",
    description: "Read production incident details and evidence. No secrets returned.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "production.incident.resolve": {
    toolId: "production.incident.resolve",
    label: "Production: Resolve Incident",
    category: "deployment",
    description: "Mark a production incident as resolved. Requires user confirmation.",
    riskLevel: "medium",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },
  "production.repair_task.create": {
    toolId: "production.repair_task.create",
    label: "Production: Create Repair Task",
    category: "deployment",
    description: "Create a repair task from a production incident. Does not mutate production directly — all deploy/payment/DNS actions still require approval.",
    riskLevel: "medium",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  // ─── Provider-neutral deployment tools ───────────────────────────────────────

  "deployment.provider.list": {
    toolId: "deployment.provider.list",
    label: "Deployment: List Providers",
    category: "deployment",
    description: "List all supported deployment providers and their capabilities. Read-only metadata — no credentials returned.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  "deployment.provider.readiness": {
    toolId: "deployment.provider.readiness",
    label: "Deployment: Provider Readiness",
    category: "deployment",
    description: "Check provider readiness: adapter status, credential presence (metadata only), and manual guide availability. Never returns raw credentials.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  "deployment.plan": {
    toolId: "deployment.plan",
    label: "Deployment: Generate Plan",
    category: "deployment",
    description: "Generate a structured deployment plan for a selected provider, including required steps, approval gates, and manual guide if adapter is a placeholder.",
    riskLevel: "low",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  "deployment.env.read": {
    toolId: "deployment.env.read",
    label: "Deployment: Read Env Vars",
    category: "deployment",
    description: "Read environment variable names from the deployment provider. Returns key names only — never raw values.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  "deployment.env.write": {
    toolId: "deployment.env.write",
    label: "Deployment: Write Env Vars",
    category: "deployment",
    description: "Write environment variables to the deployment provider. Requires vault credential, owner approval, and safe-build. Credential values are never returned in the response.",
    riskLevel: "high",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  "deployment.status.read": {
    toolId: "deployment.status.read",
    label: "Deployment: Read Status",
    category: "deployment",
    description: "Read current deployment status from the provider. Returns deploy state, last deploy time, and health — no credentials.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  "deployment.logs.read": {
    toolId: "deployment.logs.read",
    label: "Deployment: Read Logs",
    category: "deployment",
    description: "Read recent deployment or build logs from the provider. Sanitised before return — no credentials in output.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  "deployment.trigger": {
    toolId: "deployment.trigger",
    label: "Deployment: Trigger Deploy",
    category: "deployment",
    description: "Trigger a deployment on the selected provider. Requires vault credential, owner approval, and passing safe-build. Blocked for placeholder adapters.",
    riskLevel: "high",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  "deployment.domain.check": {
    toolId: "deployment.domain.check",
    label: "Deployment: Domain Check",
    category: "deployment",
    description: "Check DNS and domain configuration for the deployment provider. Read-only — no mutations.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  "deployment.manual_guide.generate": {
    toolId: "deployment.manual_guide.generate",
    label: "Deployment: Generate Manual Guide",
    category: "deployment",
    description: "Generate a step-by-step manual deployment guide for any provider, including pre-deploy checklist and post-deploy verification steps.",
    riskLevel: "low",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  // ─── Provider-specific tools ──────────────────────────────────────────────────

  "render.env.write": {
    toolId: "render.env.write",
    label: "Render: Write Env Vars",
    category: "deployment",
    description: "Write environment variables to a Render service. Requires vault credential and owner approval. Adapter is placeholder — generates manual guide instead of executing.",
    riskLevel: "high",
    permissionsRequired: ["login_required"],
    credentialProvider: "render",
    credentialKind: "api_key",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  "render.deploy.trigger": {
    toolId: "render.deploy.trigger",
    label: "Render: Trigger Deploy",
    category: "deployment",
    description: "Trigger a deployment on Render. Requires vault credential, owner approval, and passing safe-build. Adapter is placeholder — generates manual guide instead of executing.",
    riskLevel: "high",
    permissionsRequired: ["login_required"],
    credentialProvider: "render",
    credentialKind: "api_key",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  "digitalocean.env.write": {
    toolId: "digitalocean.env.write",
    label: "DigitalOcean: Write Env Vars",
    category: "deployment",
    description: "Write environment variables to a DigitalOcean App Platform app. Requires vault credential and owner approval. Adapter is placeholder — generates manual guide instead of executing.",
    riskLevel: "high",
    permissionsRequired: ["login_required"],
    credentialProvider: "digitalocean",
    credentialKind: "access_token",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  "digitalocean.deploy.trigger": {
    toolId: "digitalocean.deploy.trigger",
    label: "DigitalOcean: Trigger Deploy",
    category: "deployment",
    description: "Trigger a deployment on DigitalOcean App Platform. Requires vault credential, owner approval, and passing safe-build. Adapter is placeholder — generates manual guide instead of executing.",
    riskLevel: "high",
    permissionsRequired: ["login_required"],
    credentialProvider: "digitalocean",
    credentialKind: "access_token",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  "vercel.env.write": {
    toolId: "vercel.env.write",
    label: "Vercel: Write Env Vars",
    category: "deployment",
    description: "Write environment variables to a Vercel project. Requires vault credential and owner approval. Adapter is placeholder — generates manual guide instead of executing.",
    riskLevel: "high",
    permissionsRequired: ["login_required"],
    credentialProvider: "vercel",
    credentialKind: "access_token",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  "vercel.deploy.trigger": {
    toolId: "vercel.deploy.trigger",
    label: "Vercel: Trigger Deploy",
    category: "deployment",
    description: "Trigger a deployment on Vercel. Requires vault credential, owner approval, and passing safe-build. Adapter is placeholder — generates manual guide instead of executing.",
    riskLevel: "high",
    permissionsRequired: ["login_required"],
    credentialProvider: "vercel",
    credentialKind: "access_token",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  "sevall.env.write": {
    toolId: "sevall.env.write",
    label: "Sevall: Write Env Vars",
    category: "deployment",
    description: "Write environment variables to a Sevall service. Requires vault credential and owner approval. Adapter is placeholder — generates manual guide instead of executing.",
    riskLevel: "high",
    permissionsRequired: ["login_required"],
    credentialProvider: "sevall",
    credentialKind: "api_key",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  "sevall.deploy.trigger": {
    toolId: "sevall.deploy.trigger",
    label: "Sevall: Trigger Deploy",
    category: "deployment",
    description: "Trigger a deployment on Sevall. Requires vault credential, owner approval, and passing safe-build. Adapter is placeholder — generates manual guide instead of executing. Note: Sevall support is available as a manual-guided provider until API integration is confirmed.",
    riskLevel: "high",
    permissionsRequired: ["login_required"],
    credentialProvider: "sevall",
    credentialKind: "api_key",
    supportsDryRun: true,
    requiresApproval: true,
    requiresSafeBuild: true,
    outputsSecretValues: false,
  },

  "custom.deploy.guide": {
    toolId: "custom.deploy.guide",
    label: "Custom: Generate Deploy Guide",
    category: "deployment",
    description: "Generate a manual deployment guide for a custom/unsupported provider. User enters provider name, dashboard URL, and deployment notes. No automated mutations.",
    riskLevel: "low",
    permissionsRequired: ["login_required"],
    credentialProvider: "custom_deployment",
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
  },

  // ── Web / Search / HTTP tools ─────────────────────────────────────────────
  "search.web_fetch": {
    toolId: "search.web_fetch",
    label: "Web: Fetch URL",
    category: "data",
    description: "Fetch the content of any public URL and return the text. Use to read documentation, HTML pages, REST API responses, or raw files.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "web_fetch",
  },
  "search.web_search": {
    toolId: "search.web_search",
    label: "Web: Search the Internet",
    category: "data",
    description: "Search the web for any query and return ranked results with titles, URLs, and snippets.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "web_search",
  },
  "search.npm_search": {
    toolId: "search.npm_search",
    label: "NPM: Search Packages",
    category: "data",
    description: "Search the npm registry for packages by keyword.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "npm_search",
  },
  "search.npm_package_info": {
    toolId: "search.npm_package_info",
    label: "NPM: Package Info",
    category: "data",
    description: "Get detailed information about an npm package including version, description, dependencies, and download stats.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "npm_package_info",
  },
  "http.request": {
    toolId: "http.request",
    label: "HTTP: Request",
    category: "data",
    description: "Make any HTTP/HTTPS request (GET, POST, PUT, PATCH, DELETE) with custom headers and body. Use to call REST APIs, webhooks, or any HTTP endpoint.",
    riskLevel: "low",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "http_request",
  },

  // ── Communication tools ───────────────────────────────────────────────────
  "comms.email_send": {
    toolId: "comms.email_send",
    label: "Email: Send",
    category: "comms",
    description: "Send an email via SMTP. Requires SMTP_HOST, SMTP_USER, SMTP_PASS environment variables to be set.",
    riskLevel: "medium",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "email_send",
  },
  "comms.discord_webhook": {
    toolId: "comms.discord_webhook",
    label: "Discord: Webhook",
    category: "comms",
    description: "Post a message to a Discord channel via incoming webhook. Supports embeds and rich formatting.",
    riskLevel: "low",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "discord_webhook",
  },
  "comms.slack_webhook": {
    toolId: "comms.slack_webhook",
    label: "Slack: Webhook",
    category: "comms",
    description: "Post a message to a Slack channel via incoming webhook. Supports Block Kit blocks, attachments, and mrkdwn formatting.",
    riskLevel: "low",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "slack_webhook",
  },
  "comms.webhook_post": {
    toolId: "comms.webhook_post",
    label: "Webhook: Post with Retry",
    category: "comms",
    description: "POST a JSON payload to any webhook URL with automatic retry and optional HMAC-SHA256 signing. Use for Zapier, Make, n8n, or custom ingest endpoints.",
    riskLevel: "medium",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: true,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "webhook_post",
  },

  // ── Data tools ────────────────────────────────────────────────────────────
  "data.pdf_extract": {
    toolId: "data.pdf_extract",
    label: "PDF: Extract Text",
    category: "data",
    description: "Fetch a PDF from a URL and extract its text content for analysis or summarisation.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "pdf_extract",
  },
  "data.sql_query": {
    toolId: "data.sql_query",
    label: "SQL: Read-Only Query",
    category: "data",
    description: "Run a read-only SQL SELECT query against the project database. INSERT/UPDATE/DELETE are blocked.",
    riskLevel: "read_only",
    permissionsRequired: ["login_required"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "sql_query",
  },
  "data.rss_feed_read": {
    toolId: "data.rss_feed_read",
    label: "RSS: Read Feed",
    category: "data",
    description: "Fetch and parse an RSS 2.0 or Atom feed. Returns items with title, link, date, and summary. Use for monitoring blogs, news, GitHub releases, or any RSS source.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "rss_feed_read",
  },

  // ── Storage tools ─────────────────────────────────────────────────────────
  "storage.file_write": {
    toolId: "storage.file_write",
    label: "File: Write",
    category: "storage",
    description: "Write content to a file in the agent's temporary workspace.",
    riskLevel: "low",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "file_write",
  },
  "storage.file_read": {
    toolId: "storage.file_read",
    label: "File: Read",
    category: "storage",
    description: "Read content from a file in the agent's temporary workspace.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "file_read",
  },
  "storage.file_list": {
    toolId: "storage.file_list",
    label: "File: List",
    category: "storage",
    description: "List files in the agent's temporary workspace directory.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "file_list",
  },

  // ── Dev tools ─────────────────────────────────────────────────────────────
  "devtools.code_run": {
    toolId: "devtools.code_run",
    label: "Sandbox: Run Node.js Code",
    category: "devtools",
    description: "Execute Node.js code in an isolated sandboxed process with a timeout. Returns stdout, stderr, and exit code. Never executes shell commands or filesystem writes outside the sandbox.",
    riskLevel: "medium",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "code_run",
  },
  "devtools.text_translate": {
    toolId: "devtools.text_translate",
    label: "Text: Translate",
    category: "devtools",
    description: "Translate text between any two languages using Groq LLM with MyMemory API fallback.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "text_translate",
  },
  "devtools.diff_generate": {
    toolId: "devtools.diff_generate",
    label: "Diff: Generate",
    category: "devtools",
    description: "Generate a unified diff between two text strings.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "diff_generate",
  },
  "devtools.memory_store": {
    toolId: "devtools.memory_store",
    label: "Memory: Store",
    category: "devtools",
    description: "Store a key-value pair in the agent's in-session memory for recall later.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "memory_store",
  },
  "devtools.memory_recall": {
    toolId: "devtools.memory_recall",
    label: "Memory: Recall",
    category: "devtools",
    description: "Recall a previously stored key-value pair from the agent's in-session memory.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "memory_recall",
  },
  "devtools.memory_clear": {
    toolId: "devtools.memory_clear",
    label: "Memory: Clear",
    category: "devtools",
    description: "Clear all or a specific key from the agent's in-session memory.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "memory_clear",
  },

  // ── Security audit tools ──────────────────────────────────────────────────
  "security.headers_audit": {
    toolId: "security.headers_audit",
    label: "Security: HTTP Headers Audit",
    category: "security",
    description: "Fetch HTTP response headers for a URL and audit them for missing or misconfigured security headers (CSP, HSTS, X-Frame-Options, etc.).",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "headers_audit",
  },
  "security.ssl_check": {
    toolId: "security.ssl_check",
    label: "Security: SSL/TLS Check",
    category: "security",
    description: "Check the SSL/TLS certificate and configuration for a domain. Returns certificate validity, expiry, protocol version, and cipher suite information.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "ssl_check",
  },
  "security.cors_check": {
    toolId: "security.cors_check",
    label: "Security: CORS Check",
    category: "security",
    description: "Test CORS policy on an endpoint by sending preflight and actual cross-origin requests. Identifies overly permissive configurations.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "cors_check",
  },
  "security.secrets_scan": {
    toolId: "security.secrets_scan",
    label: "Security: Secrets Scan",
    category: "security",
    description: "Scan text content (code, config files, logs) for accidentally exposed secrets, API keys, tokens, passwords, or connection strings using pattern matching.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "secrets_scan",
  },
  "security.password_audit": {
    toolId: "security.password_audit",
    label: "Security: Password Strength Audit",
    category: "security",
    description: "Analyse a password or password policy for strength, entropy, and compliance with NIST 800-63b guidelines. Never logs or stores the password.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "password_audit",
  },
  "security.url_reputation": {
    toolId: "security.url_reputation",
    label: "Security: URL Reputation Check",
    category: "security",
    description: "Check a URL or domain for known malicious indicators, phishing patterns, suspicious TLDs, and redirect chains.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "url_reputation",
  },

  // ── Network / recon tools ─────────────────────────────────────────────────
  "network.dns_lookup": {
    toolId: "network.dns_lookup",
    label: "Network: DNS Lookup",
    category: "network",
    description: "Perform DNS lookups for a domain. Returns A, AAAA, CNAME, MX, TXT, NS, and SOA records.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "dns_lookup",
  },
  "network.whois_lookup": {
    toolId: "network.whois_lookup",
    label: "Network: WHOIS Lookup",
    category: "network",
    description: "Retrieve WHOIS registration data for a domain: registrar, creation/expiry dates, name servers, and registrant info.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "whois_lookup",
  },
  "network.port_check": {
    toolId: "network.port_check",
    label: "Network: Port Check",
    category: "network",
    description: "Check whether TCP ports are open or closed on a host. Use to verify service availability or identify exposed services.",
    riskLevel: "low",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "port_check",
  },
  "network.cve_search": {
    toolId: "network.cve_search",
    label: "Network: CVE Search",
    category: "network",
    description: "Search the NVD (National Vulnerability Database) for CVEs by keyword, package name, or CVE ID. Returns severity, description, and affected versions.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "cve_search",
  },
  "network.dependency_audit": {
    toolId: "network.dependency_audit",
    label: "Network: Dependency Audit",
    category: "network",
    description: "Audit a list of npm package dependencies for known vulnerabilities by querying the npm audit API.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "dependency_audit",
  },

  // ── Utility tools ─────────────────────────────────────────────────────────
  "utility.hash_text": {
    toolId: "utility.hash_text",
    label: "Utility: Hash Text",
    category: "utility",
    description: "Compute SHA-256, SHA-512, SHA-1, or MD5 hash of any text.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "hash_text",
  },
  "utility.base64_encode": {
    toolId: "utility.base64_encode",
    label: "Utility: Base64 Encode",
    category: "utility",
    description: "Encode text to Base64 (standard or URL-safe).",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "base64_encode",
  },
  "utility.base64_decode": {
    toolId: "utility.base64_decode",
    label: "Utility: Base64 Decode",
    category: "utility",
    description: "Decode a Base64 string back to text. Handles both standard and URL-safe Base64.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "base64_decode",
  },
  "utility.jwt_decode": {
    toolId: "utility.jwt_decode",
    label: "Utility: JWT Decode",
    category: "utility",
    description: "Decode and inspect a JWT token header and payload. Does NOT verify the signature — use for debugging and auditing only.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "jwt_decode",
  },
  "utility.uuid_generate": {
    toolId: "utility.uuid_generate",
    label: "Utility: UUID Generate",
    category: "utility",
    description: "Generate one or more cryptographically random UUID v4 values.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "uuid_generate",
  },
  "utility.regex_test": {
    toolId: "utility.regex_test",
    label: "Utility: Regex Test",
    category: "utility",
    description: "Test a regular expression against text. Returns whether it matches, all captured groups, and all matches if global flag is set.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "regex_test",
  },
  "utility.json_validate": {
    toolId: "utility.json_validate",
    label: "Utility: JSON Validate",
    category: "utility",
    description: "Validate that a string is valid JSON and optionally check for required top-level keys.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "json_validate",
  },
  "utility.csv_parse": {
    toolId: "utility.csv_parse",
    label: "Utility: CSV Parse",
    category: "utility",
    description: "Parse a CSV string into a JSON array of objects. First row is treated as headers.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "csv_parse",
  },
  "utility.markdown_to_html": {
    toolId: "utility.markdown_to_html",
    label: "Utility: Markdown to HTML",
    category: "utility",
    description: "Convert Markdown text to HTML. Supports headings, bold, italic, code blocks, lists, links, images, blockquotes, and horizontal rules.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "markdown_to_html",
  },
  "utility.qr_code_generate": {
    toolId: "utility.qr_code_generate",
    label: "Utility: QR Code Generate",
    category: "utility",
    description: "Generate a QR code image URL for any text, URL, or data. Returns an embeddable image URL.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "qr_code_generate",
  },
  "utility.calendar_event_create": {
    toolId: "utility.calendar_event_create",
    label: "Utility: Calendar Event (.ics)",
    category: "utility",
    description: "Generate an iCal (.ics) calendar event string (RFC 5545). Output can be sent by email or saved as a .ics file for users to add to their calendars.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "calendar_event_create",
  },

  // ── Smoke test tools ──────────────────────────────────────────────────────
  "testing.smoke_test": {
    toolId: "testing.smoke_test",
    label: "Testing: Smoke Test",
    category: "testing",
    description: "Run a single smoke test against an HTTP endpoint. Checks status code, optional body content, and response time. Use after deployments to verify services are up.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "smoke_test",
  },
  "testing.smoke_test_suite": {
    toolId: "testing.smoke_test_suite",
    label: "Testing: Smoke Test Suite",
    category: "testing",
    description: "Run a batch of smoke tests in parallel and get a single pass/fail summary report. Ideal for post-deployment verification checklists.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "smoke_test_suite",
  },
  "testing.smoke_test_page": {
    toolId: "testing.smoke_test_page",
    label: "Testing: Smoke Test Page",
    category: "testing",
    description: "Load a web page and verify that specific text or HTML elements are present (or absent) in the response.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "smoke_test_page",
  },

  // ── Date/time tools ───────────────────────────────────────────────────────
  "devtools.datetime_parse": {
    toolId: "devtools.datetime_parse",
    label: "DateTime: Parse",
    category: "devtools",
    description: "Parse any date/time string into ISO 8601, Unix timestamp, and full component breakdown (year, month, day, hour, minute, second, weekday).",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "datetime_parse",
  },
  "devtools.datetime_format": {
    toolId: "devtools.datetime_format",
    label: "DateTime: Format",
    category: "devtools",
    description: "Format a date/time with a custom pattern and optional timezone conversion.",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "datetime_format",
  },
  "devtools.datetime_diff": {
    toolId: "devtools.datetime_diff",
    label: "DateTime: Diff",
    category: "devtools",
    description: "Calculate the difference between two dates in all units (seconds, minutes, hours, days, weeks, months, years).",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "datetime_diff",
  },
  "devtools.cron_next": {
    toolId: "devtools.cron_next",
    label: "DateTime: Cron Next",
    category: "devtools",
    description: "Calculate the next N execution times for a cron expression. Supports standard 5-field cron and aliases (@daily, @hourly, etc.).",
    riskLevel: "read_only",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "cron_next",
  },

  // ── Inference tool ────────────────────────────────────────────────────────
  "inference.generate_text": {
    toolId: "inference.generate_text",
    label: "AI: Generate Text (Groq)",
    category: "inference",
    description: "Use Groq LLM to generate text, summarise content, answer questions, translate, classify, or perform any language task as a focused sub-call within an agent's tool loop.",
    riskLevel: "low",
    permissionsRequired: ["none"],
    credentialProvider: null,
    credentialKind: null,
    supportsDryRun: false,
    requiresApproval: false,
    requiresSafeBuild: false,
    outputsSecretValues: false,
    executionName: "generate_text",
  },
};

export function getToolById(toolId: string): ToolDefinition | undefined {
  return TOOL_REGISTRY[toolId];
}

export function getAllTools(): ToolDefinition[] {
  return Object.values(TOOL_REGISTRY);
}

export function getToolsByCategory(category: ToolCategory): ToolDefinition[] {
  return getAllTools().filter((t) => t.category === category);
}

export const VALID_RISK_LEVELS: RiskLevel[] = ["read_only", "low", "medium", "high", "destructive"];
export const TOOL_IDS = Object.keys(TOOL_REGISTRY);
