import { Router, type IRouter } from "express";
import { pool } from "@workspace/db";

const router: IRouter = Router();

type Row = Record<string, unknown>;

type Crew = {
  id: string;
  name: string;
  estimatedCredits: number;
  requiredConnectors: string[];
  approvalRequired: boolean;
  safeModeDefault: boolean;
};

const CREWS: Crew[] = [
  { id: "website-doctor", name: "Website Doctor Crew", estimatedCredits: 420, requiredConnectors: ["github", "browser"], approvalRequired: true, safeModeDefault: true },
  { id: "security-audit", name: "Security Audit Crew", estimatedCredits: 520, requiredConnectors: ["github"], approvalRequired: true, safeModeDefault: true },
  { id: "railway-deploy", name: "Railway Deployment Crew", estimatedCredits: 360, requiredConnectors: ["railway", "github"], approvalRequired: true, safeModeDefault: true },
  { id: "github-repair", name: "GitHub Repair Crew", estimatedCredits: 480, requiredConnectors: ["github"], approvalRequired: true, safeModeDefault: true },
  { id: "stripe-billing", name: "Stripe/Billing Audit Crew", estimatedCredits: 390, requiredConnectors: ["stripe"], approvalRequired: true, safeModeDefault: true },
  { id: "ux-review", name: "UX Review Crew", estimatedCredits: 260, requiredConnectors: ["browser"], approvalRequired: false, safeModeDefault: true },
  { id: "mobile-qa", name: "Mobile QA Crew", estimatedCredits: 280, requiredConnectors: ["browser"], approvalRequired: false, safeModeDefault: true },
  { id: "full-build", name: "Full Build Crew", estimatedCredits: 900, requiredConnectors: ["github", "railway", "provider"], approvalRequired: true, safeModeDefault: true },
];

function hasEnv(name: string): boolean {
  const value = process.env[name];
  return Boolean(value && value.trim());
}

function connectorStatus(): Record<string, boolean> {
  return {
    github: hasEnv("GITHUB_TOKEN") || hasEnv("GH_TOKEN"),
    railway: hasEnv("RAILWAY_TOKEN") || hasEnv("RAILWAY_API_TOKEN"),
    stripe: hasEnv("STRIPE_SECRET_KEY") && hasEnv("STRIPE_WEBHOOK_SECRET"),
    smtp: ["SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASS", "SMTP_FROM"].every(hasEnv),
    provider: ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GEMINI_API_KEY", "GROQ_API_KEY"].some(hasEnv),
    browser: true,
  };
}

function crewById(id: unknown): Crew | null {
  return CREWS.find((crew) => crew.id === String(id)) ?? null;
}

function estimateCredits(goal: string, crew?: Crew | null): number {
  if (crew) return crew.estimatedCredits;
  const words = goal.trim().split(/\s+/).filter(Boolean).length;
  if (words > 60) return 620;
  if (words > 30) return 420;
  return 260;
}

async function count(sqlText: string, values: unknown[]): Promise<number> {
  try {
    const result = await pool.query<{ count: string | number }>(sqlText, values);
    return Number(result.rows[0]?.count ?? 0);
  } catch {
    return 0;
  }
}

async function rows(sqlText: string, values: unknown[]): Promise<Row[]> {
  try {
    const result = await pool.query<Row>(sqlText, values);
    return result.rows;
  } catch {
    return [];
  }
}

function grade(score: number): "excellent" | "good" | "needs-review" | "blocked" {
  if (score >= 90) return "excellent";
  if (score >= 75) return "good";
  if (score >= 50) return "needs-review";
  return "blocked";
}

function markdownEvidencePack(payload: {
  session: Row | null;
  tasks: Row[];
  approvals: Row[];
  creditReceipts: Row[];
  risks: string[];
  quality: { score: number; grade: string; reasons: string[]; recommendedNextAction: string };
}): string {
  const sessionTitle = String(payload.session?.goal ?? "VIBA session");
  const lines = [
    `# VIBA Client Evidence Pack`,
    "",
    `## Session`,
    `Goal: ${sessionTitle}`,
    `Status: ${String(payload.session?.status ?? "unknown")}`,
    "",
    `## Quality Score`,
    `Score: ${payload.quality.score}/100`,
    `Grade: ${payload.quality.grade}`,
    `Next action: ${payload.quality.recommendedNextAction}`,
    "",
    `## Completed Tasks`,
    ...payload.tasks.map((task) => `- ${String(task.title ?? task.id)} — ${String(task.status ?? "unknown")}`),
    "",
    `## Approvals`,
    ...(payload.approvals.length ? payload.approvals.map((approval) => `- ${String(approval.title ?? approval.id)} — ${String(approval.status ?? "unknown")}`) : ["- No approval records found."]),
    "",
    `## Credit Receipt Summary`,
    `Receipts: ${payload.creditReceipts.length}`,
    "",
    `## Risks / Follow-up`,
    ...(payload.risks.length ? payload.risks.map((risk) => `- ${risk}`) : ["- No unresolved risks detected from stored records."]),
    "",
    `Generated by VIBA. Client-safe export: no secrets, no raw provider keys, no private stack traces.`,
  ];
  return `${lines.join("\n")}\n`;
}

async function qualityForSession(sessionId: number) {
  const taskTotal = await count("SELECT COUNT(*)::int AS count FROM tasks WHERE session_id = $1", [sessionId]);
  const taskDone = await count("SELECT COUNT(*)::int AS count FROM tasks WHERE session_id = $1 AND status IN ('completed','done','success')", [sessionId]);
  const approvalsOpen = await count("SELECT COUNT(*)::int AS count FROM approvals WHERE session_id = $1 AND status NOT IN ('approved','rejected','resolved')", [sessionId]);
  const blockers = await count("SELECT COUNT(*)::int AS count FROM tasks WHERE session_id = $1 AND status ILIKE '%block%'", [sessionId]);
  const budgetHits = await count("SELECT COUNT(*)::int AS count FROM audit_logs WHERE session_id = $1 AND event_type IN ('session_budget_cap_reached','budget_cap_reached')", [sessionId]);
  const providerFailures = await count("SELECT COUNT(*)::int AS count FROM audit_logs WHERE session_id = $1 AND (event_type ILIKE '%provider%fail%' OR event_type ILIKE '%adapter%fallback%')", [sessionId]);
  const proofMessages = await count("SELECT COUNT(*)::int AS count FROM messages WHERE session_id = $1 AND (metadata->>'type' = 'proof_report' OR content ILIKE '%proof report%')", [sessionId]);

  let score = 50;
  const reasons: string[] = [];

  if (taskTotal > 0) {
    const completion = Math.round((taskDone / taskTotal) * 30);
    score += completion;
    reasons.push(`${taskDone}/${taskTotal} tasks completed.`);
  } else {
    reasons.push("No task records found yet.");
  }

  if (approvalsOpen === 0) score += 8; else { score -= approvalsOpen * 5; reasons.push(`${approvalsOpen} approval item(s) still open.`); }
  if (blockers === 0) score += 8; else { score -= blockers * 8; reasons.push(`${blockers} blocker task(s) detected.`); }
  if (proofMessages > 0) { score += 6; reasons.push("Proof report evidence exists."); } else reasons.push("Proof report evidence not detected yet.");
  if (budgetHits > 0) { score -= 8; reasons.push(`${budgetHits} budget cap event(s) detected.`); }
  if (providerFailures > 0) { score -= 6; reasons.push(`${providerFailures} provider fallback/failure event(s) detected.`); }

  score = Math.max(0, Math.min(100, score));
  const label = grade(score);
  const recommendedNextAction = label === "blocked"
    ? "Open Recovery and resolve blockers before continuing."
    : label === "needs-review"
      ? "Review proof report, approvals, and unresolved risks before client delivery."
      : "Ready for owner review and client-safe export.";
  return { score, grade: label, reasons, recommendedNextAction };
}

router.post("/sessions/preflight", async (req, res): Promise<void> => {
  const body = req.body as { goal?: string; crewId?: string; mode?: string };
  const goal = typeof body.goal === "string" ? body.goal.trim() : "";
  const crew = crewById(body.crewId);
  const requiredConnectors = crew?.requiredConnectors ?? (goal.toLowerCase().includes("railway") ? ["railway", "github"] : goal.toLowerCase().includes("stripe") ? ["stripe"] : ["github"]);
  const connectorMap = connectorStatus();
  const missingConnectors = requiredConnectors.filter((connector) => !connectorMap[connector]);
  const paidProvidersEnabled = connectorMap.provider;
  const blockers = goal ? [] : ["A session goal is required before starting."];
  if (missingConnectors.length) blockers.push(`Missing connector(s): ${missingConnectors.join(", ")}.`);
  const warnings = paidProvidersEnabled
    ? ["At least one paid provider key is configured. Live use still requires approval and budget cap."]
    : ["No paid provider is configured. Session can run in simulation/local-safe mode only."];

  res.json({
    estimatedCredits: estimateCredits(goal, crew),
    requiredConnectors,
    missingConnectors,
    paidProvidersEnabled,
    approvalRequired: crew?.approvalRequired ?? true,
    safeModeDefault: crew?.safeModeDefault ?? true,
    canStart: blockers.length === 0,
    blockers,
    warnings,
    mode: body.mode ?? "simulation",
  });
});

router.get("/sessions/:id/quality-score", async (req, res): Promise<void> => {
  const sessionId = Number.parseInt(String(req.params.id), 10);
  if (!Number.isFinite(sessionId) || sessionId <= 0) { res.status(400).json({ error: "invalid_session_id" }); return; }
  res.json(await qualityForSession(sessionId));
});

router.get("/sessions/:id/evidence-pack", async (req, res): Promise<void> => {
  const sessionId = Number.parseInt(String(req.params.id), 10);
  if (!Number.isFinite(sessionId) || sessionId <= 0) { res.status(400).json({ error: "invalid_session_id" }); return; }
  const sessionRows = await rows("SELECT id, goal, status, created_at, updated_at FROM sessions WHERE id = $1 LIMIT 1", [sessionId]);
  if (!sessionRows[0]) { res.status(404).json({ error: "session_not_found" }); return; }
  const tasks = await rows("SELECT id, title, status, type, created_at FROM tasks WHERE session_id = $1 ORDER BY id ASC", [sessionId]);
  const approvals = await rows("SELECT id, title, status, created_at FROM approvals WHERE session_id = $1 ORDER BY id ASC", [sessionId]);
  const creditReceipts = await rows("SELECT id, created_at, metadata FROM messages WHERE session_id = $1 AND metadata->>'type' = 'action_credit_receipt' ORDER BY id ASC", [sessionId]);
  const risks = (await rows("SELECT description FROM audit_logs WHERE session_id = $1 AND event_type ILIKE '%risk%' ORDER BY id ASC", [sessionId])).map((row) => String(row.description));
  const quality = await qualityForSession(sessionId);
  const payload = { session: sessionRows[0], tasks, approvals, creditReceipts, risks, quality };
  res.json({ ...payload, redacted: true, markdown: markdownEvidencePack(payload) });
});

router.post("/providers/:provider/safe-test", async (req, res): Promise<void> => {
  const provider = String(req.params.provider || "").toLowerCase();
  const paid = ["openai", "anthropic", "gemini", "groq"].includes(provider);
  const envName = provider === "openai" ? "OPENAI_API_KEY" : provider === "anthropic" ? "ANTHROPIC_API_KEY" : provider === "gemini" ? "GEMINI_API_KEY" : provider === "groq" ? "GROQ_API_KEY" : null;
  if (paid) {
    res.json({ provider, configured: envName ? hasEnv(envName) : false, enabled: false, paidCallMade: false, message: envName && hasEnv(envName) ? "Key/config present. No paid inference call was made." : "Provider key/config missing. No paid inference call was made." });
    return;
  }
  const endpoint = typeof (req.body as { endpoint?: unknown })?.endpoint === "string" ? String((req.body as { endpoint: string }).endpoint) : process.env.LOCAL_ENDPOINT || process.env.CUSTOM_ENDPOINT || "";
  if (!endpoint) { res.json({ provider, configured: false, enabled: false, paidCallMade: false, message: "No local/custom endpoint configured." }); return; }
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 5000);
    const response = await fetch(endpoint, { method: "GET", signal: controller.signal }).finally(() => clearTimeout(timeout));
    res.json({ provider, configured: true, enabled: response.ok, paidCallMade: false, statusCode: response.status, message: `Endpoint responded with HTTP ${response.status}.` });
  } catch (error) {
    res.json({ provider, configured: true, enabled: false, paidCallMade: false, message: error instanceof Error ? error.message : "Endpoint unreachable." });
  }
});

router.get("/release-notes/latest", (_req, res): void => {
  const changedRoutes = ["/providers", "/connectors", "/self-audit", "/crews", "/team", "/clients", "/usage", "/recovery", "/doctor/trends", "/market-readiness", "/sessions/:id/timeline", "/sessions/:id/map"];
  const newFeatures = ["Provider and connector command surfaces", "Market readiness dashboard", "Public demo pages", "Client-safe share reports", "Session timeline and map", "Preflight run card API", "Run quality score", "Client evidence pack export", "Provider safe-mode test harness"];
  const manualSetupNeeded = ["Railway production env vars", "Stripe test products/prices/webhook", "SMTP credentials", "Custom domain and PUBLIC_ORIGIN", "Production smoke test"];
  const knownLimitations = ["Live provider calls remain approval-gated and budget-capped.", "Repair PR creation requires GitHub credentials and explicit confirmation.", "Stripe live mode must be owner-approved separately."];
  const controlledLaunchNotes = ["Use Railway domain until custom domain is verified.", "Keep providers default-off until budget caps are confirmed.", "Start with 5-10 controlled users and collect proof reports."];
  const markdown = [`# VIBA Release Notes`, "", `## New features`, ...newFeatures.map((item) => `- ${item}`), "", `## Changed routes`, ...changedRoutes.map((item) => `- ${item}`), "", `## Manual setup needed`, ...manualSetupNeeded.map((item) => `- ${item}`), "", `## Known limitations`, ...knownLimitations.map((item) => `- ${item}`), "", `## Controlled launch notes`, ...controlledLaunchNotes.map((item) => `- ${item}`)].join("\n");
  res.json({ newFeatures, changedRoutes, manualSetupNeeded, knownLimitations, controlledLaunchNotes, markdown, generatedAt: new Date().toISOString() });
});

export default router;
