import { Router, type IRouter } from "express";
import healthRouter from "./health";
import sessionAccessRouter from "./sessionPrivacy";
import coreDefaultsRouter from "./coreDefaults";
import backgroundSessionsRouter from "./backgroundSessions";
import sessionsRouter from "./sessions";
import attachmentsRouter from "./attachments";
import selfRepairAutoRouter from "./selfRepairAuto";
import selfAuditMergeSafetyRouter from "./selfAuditMergeSafety";
import selfAuditRouter from "./selfAudit";
import settingsRouter from "./settings";
import statsRouter from "./stats";
import circuitStatusRouter from "./circuitStatus";
import workbenchRouter from "../workbench/serverRoutes";
import authRouter from "./auth";
import stripeRouter from "./stripe";
import billingRouter from "./billing";
import githubRouter from "./github";
import connectionsRouter from "./connections";
import vibaKeysRouter from "./credentials";
import webResearchRouter from "./webResearch";
import pricingResearchRouter from "./pricingResearch";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(sessionAccessRouter);
router.use(coreDefaultsRouter);
router.use(backgroundSessionsRouter);
router.use(sessionsRouter);
router.use(attachmentsRouter);
router.use(selfRepairAutoRouter);
router.use(selfAuditMergeSafetyRouter);
router.use(selfAuditRouter);
router.use(settingsRouter);
router.use(statsRouter);
router.use(circuitStatusRouter);
router.use(workbenchRouter);
router.use(stripeRouter);
router.use(billingRouter);
router.use(githubRouter);
router.use(connectionsRouter);
router.use(vibaKeysRouter);
router.use(webResearchRouter);
router.use(pricingResearchRouter);

export default router;
