import { Router, type IRouter } from "express";
import healthRouter from "./health";
import sessionsRouter from "./sessions";
import settingsRouter from "./settings";
import statsRouter from "./stats";
import circuitStatusRouter from "./circuitStatus";
import workbenchRouter from "../workbench/serverRoutes";
import authRouter from "./auth";
import stripeRouter from "./stripe";
import billingRouter from "./billing";
import githubRouter from "./github";
import sessionAccessRouter from "./sessionPrivacy";
import coreDefaultsRouter from "./coreDefaults";
import backgroundSessionsRouter from "./backgroundSessions";
import attachmentsRouter from "./attachments";
import selfRepairAutoRouter from "./selfRepairAuto";
import selfAuditMergeSafetyRouter from "./selfAuditMergeSafety";
import selfAuditRouter from "./selfAudit";
import annualBillingRouter from "./annualBilling";
import connectionsRouter from "./connections";
import vibaKeysRouter from "./credentials";
import webResearchRouter from "./webResearch";
import pricingResearchRouter from "./pricingResearch";
import providersRouter from "./providers";
import doctorRouter from "./doctor";
import marketCompletionRouter from "./marketCompletion";
import assistedBrowserRouter from "./assistedBrowser";
import railwayConnectorRouter from "./railwayConnector";
import renderConnectorRouter from "./renderConnector";
import customAiCredentialsRouter from "./customAiCredentials";
import businessSecurityRouter from "./businessSecurity";
import agentCommsConsoleRouter from "./agentCommsConsole";
import taskIntakeRouter from "./taskIntake";
import toolBrokerRouter from "./toolBroker";
import agentRuntimeRouter from "./agentRuntime";
import qaReleaseGateRouter from "./qaReleaseGate";
import projectImportRouter from "./projectImport";
import productionOpsRouter from "./productionOps";
import deploymentProvidersRouter from "./deploymentProviders";
import securityRouter from "./security";
import domainSetupRouter from "./domainSetup";
import setupRunnerRouter from "./setupRunner";
import agentEvaluationRouter from "./agentEvaluation";
import costControlRouter from "./costControl";
import betaChaosRouter from "./betaChaos";
import launchReadinessRouter from "./launchReadiness";
import proofReportRouter from "./proofReport";
import valueRouterRouter from "./valueRouter";
import betaTesterRouter from "./betaTester";
import accountRouter from "./account";
import seoRouter from "./seo";
import marketingRouter from "./marketing";
import advertisingRouter from "./advertising";
import contentCreatorRouter from "./contentCreator";
import userBrowserRouter from "./userBrowserRouter";
import aiOptimizerRouter from "./aiOptimizer";
import aiBudgetsRouter from "./aiBudgets";
import aiModelsRouter from "./aiModels";
import projectMemoryRouter from "./projectMemory";

const router: IRouter = Router();

// auth routes are registered first and bypass the ACCESS_TOKEN gate in app.ts
router.use(authRouter);
router.use(healthRouter);
router.use(sessionAccessRouter);
router.use(coreDefaultsRouter);
router.use(backgroundSessionsRouter);
router.use(sessionsRouter);
router.use(settingsRouter);
router.use(statsRouter);
router.use(circuitStatusRouter);
router.use(workbenchRouter);
router.use(stripeRouter);
router.use(annualBillingRouter);
router.use(billingRouter);
router.use(githubRouter);
router.use(connectionsRouter);
router.use(vibaKeysRouter);
router.use(webResearchRouter);
router.use(pricingResearchRouter);
router.use(providersRouter);
router.use(doctorRouter);
router.use(marketCompletionRouter);
router.use(assistedBrowserRouter);
router.use(railwayConnectorRouter);
router.use(renderConnectorRouter);
router.use(customAiCredentialsRouter);
router.use(businessSecurityRouter);
router.use(agentCommsConsoleRouter);
router.use(taskIntakeRouter);
router.use(toolBrokerRouter);
router.use(agentRuntimeRouter);
router.use(qaReleaseGateRouter);
router.use(projectImportRouter);
router.use(productionOpsRouter);
router.use(deploymentProvidersRouter);
router.use(securityRouter);
router.use(domainSetupRouter);
router.use(setupRunnerRouter);
router.use(agentEvaluationRouter);
router.use(costControlRouter);
router.use(betaChaosRouter);
router.use(launchReadinessRouter);
router.use(proofReportRouter);
router.use(valueRouterRouter);
router.use(betaTesterRouter);
router.use(accountRouter);
router.use(seoRouter);
router.use(marketingRouter);
router.use(advertisingRouter);
router.use(contentCreatorRouter);
router.use(userBrowserRouter);
router.use(aiOptimizerRouter);
router.use(aiBudgetsRouter);
router.use(aiModelsRouter);
router.use(projectMemoryRouter);

export default router;
