import { Router, type IRouter } from "express";
import healthRouter from "./health";
import sessionsRouter from "./sessions";
import sessionSecurityBoundary from "../middlewares/sessionSecurityBoundary";
import settingsRouter from "./settings";
import statsRouter from "./stats";
import circuitStatusRouter from "./circuitStatus";
import workbenchRouter from "../workbench/serverRoutes";
import stripeRouter from "./stripe";
import billingRouter from "./billing";
import githubRouter from "./github";
import sessionAccessRouter from "./sessionPrivacy";
import coreDefaultsRouter from "./coreDefaults";
import backgroundSessionsRouter from "./backgroundSessions";
import attachmentsRouter from "./attachments";
import selfRepairAutoRouter from "./selfRepairAuto";
import selfAuditMergeSafetyRouter from "./selfAuditMergeSafety";
import selfAuditRouter from "./selfAudit";
import annualBillingRouter from "./annualBilling";
import connectionsRouter from "./connections";
import vibaKeysRouter from "./credentials";
import webResearchRouter from "./webResearch";
import pricingResearchRouter from "./pricingResearch";
import providersRouter from "./providers";
import doctorRouter from "./doctor";
import assistedBrowserRouter from "./assistedBrowser";
import railwayConnectorRouter from "./railwayConnector";
import renderConnectorRouter from "./renderConnector";
import customAiCredentialsRouter from "./customAiCredentials";
import businessSecurityRouter from "./businessSecurity";
import agentCommsConsoleRouter from "./agentCommsConsole";
import taskIntakeRouter from "./taskIntake";
import toolBrokerRouter from "./toolBroker";
import setupRunnerRouter from "./setupRunner";
import agentEvaluationRouter from "./agentEvaluation";
import costControlRouter from "./costControl";
import betaChaosRouter from "./betaChaos";
import proofReportRouter from "./proofReport";
import valueRouterRouter from "./valueRouter";
import accountRouter from "./account";
import fileBuildSafetyRouter from "./fileBuildSafety";
import vastaiConnectorRouter from "./vastaiConnector";
import appPublisherRouter from "./appPublisher";

const router: IRouter = Router();

router.use(healthRouter);
router.use(sessionAccessRouter);
router.use(coreDefaultsRouter);
router.use(backgroundSessionsRouter);
router.use(sessionSecurityBoundary);
router.use(sessionsRouter);
router.use(attachmentsRouter);
router.use(selfRepairAutoRouter);
router.use(selfAuditMergeSafetyRouter);
router.use(selfAuditRouter);
router.use(settingsRouter);
router.use(statsRouter);
router.use(circuitStatusRouter);
router.use(workbenchRouter);
router.use(stripeRouter);
router.use(annualBillingRouter);
router.use(billingRouter);
router.use(githubRouter);
router.use(connectionsRouter);
router.use(vibaKeysRouter);
router.use(webResearchRouter);
router.use(pricingResearchRouter);
router.use(providersRouter);
router.use(doctorRouter);
router.use(assistedBrowserRouter);
router.use(railwayConnectorRouter);
router.use(renderConnectorRouter);
router.use(customAiCredentialsRouter);
router.use(businessSecurityRouter);
router.use(agentCommsConsoleRouter);
router.use(taskIntakeRouter);
router.use(toolBrokerRouter);
router.use(setupRunnerRouter);
router.use(agentEvaluationRouter);
router.use(costControlRouter);
router.use(betaChaosRouter);
router.use(proofReportRouter);
router.use(valueRouterRouter);
router.use(accountRouter);
router.use(fileBuildSafetyRouter);
router.use(vastaiConnectorRouter);
router.use(appPublisherRouter);

export default router;
