#!/usr/bin/env node

import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const repoRoot = process.cwd();
const frontendRoot = path.join(repoRoot, "artifacts", "bridge-ai");
const publicAssetsRoot = path.join(frontendRoot, "public", "assets");
const reportPath = path.join(repoRoot, "ASSET_ORGANISATION_REPORT.md");
const apply = process.argv.includes("--apply");

const VISUAL_EXTENSIONS = new Set([
  ".png", ".jpg", ".jpeg", ".webp", ".gif", ".svg", ".ico", ".avif",
]);

const CATEGORIES = [
  "backgrounds",
  "brand",
  "icons",
  "illustrations",
  "source-boards",
  "miscellaneous",
];

function sha256(filePath) {
  return crypto.createHash("sha256").update(fs.readFileSync(filePath)).digest("hex");
}

function classify(fileName) {
  const name = fileName.toLowerCase();

  if (/(source[-_ ]?board|mood[-_ ]?board|reference[-_ ]?sheet|contact[-_ ]?sheet|sprite[-_ ]?sheet|design[-_ ]?board)/.test(name)) {
    return "source-boards";
  }
  if (/(background|\bbg\b|backdrop|wallpaper|texture|gradient|hero[-_ ]?(bg|background)|scene)/.test(name)) {
    return "backgrounds";
  }
  if (/(viba|leego|logo|wordmark|brand|favicon|all[-_ ]?as[-_ ]?one|app[-_ ]?mark)/.test(name)) {
    return "brand";
  }
  if (/(icon|glyph|symbol|badge|provider|integration|github|google|openai|claude|gemini|groq|discord|slack|stripe|vercel|render|railway)/.test(name)) {
    return "icons";
  }
  if (/(illustration|artwork|character|mascot|agent|robot|feature|dashboard|workflow|orchestration|automation)/.test(name)) {
    return "illustrations";
  }
  return "miscellaneous";
}

function uniqueDestination(directory, fileName) {
  const extension = path.extname(fileName);
  const stem = path.basename(fileName, extension);
  let candidate = path.join(directory, fileName);
  let index = 2;
  while (fs.existsSync(candidate)) {
    candidate = path.join(directory, `${stem}-${index}${extension}`);
    index += 1;
  }
  return candidate;
}

function walk(directory) {
  const output = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const absolutePath = path.join(directory, entry.name);
    if (entry.isDirectory()) output.push(...walk(absolutePath));
    else output.push(absolutePath);
  }
  return output;
}

function replaceReferences(moves) {
  const searchableRoots = [
    path.join(frontendRoot, "src"),
    path.join(frontendRoot, "public"),
    path.join(frontendRoot, "index.html"),
  ];
  const textExtensions = new Set([
    ".ts", ".tsx", ".js", ".jsx", ".css", ".scss", ".html", ".json", ".webmanifest", ".md",
  ]);

  const files = [];
  for (const target of searchableRoots) {
    if (!fs.existsSync(target)) continue;
    const stat = fs.statSync(target);
    if (stat.isDirectory()) files.push(...walk(target));
    else files.push(target);
  }

  let changedFiles = 0;
  for (const filePath of files) {
    if (!textExtensions.has(path.extname(filePath).toLowerCase())) continue;
    let content = fs.readFileSync(filePath, "utf8");
    const original = content;

    for (const move of moves) {
      const oldName = path.basename(move.from);
      const newPublicPath = `/assets/${move.category}/${path.basename(move.to)}`;
      const escaped = oldName.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      content = content.replace(new RegExp(`(?:\\.\\.?/)*${escaped}`, "g"), newPublicPath);
      content = content.replace(new RegExp(`/${escaped}`, "g"), newPublicPath);
    }

    if (content !== original) {
      changedFiles += 1;
      if (apply) fs.writeFileSync(filePath, content);
    }
  }
  return changedFiles;
}

function writeAssetRegistry(moves) {
  const registryPath = path.join(frontendRoot, "src", "lib", "assets.generated.ts");
  const important = moves.filter(({ category }) => category === "brand" || category === "backgrounds" || category === "icons");
  const groups = Object.fromEntries(CATEGORIES.map((category) => [category, []]));

  for (const move of important) {
    const key = path.basename(move.to, path.extname(move.to))
      .replace(/[^a-zA-Z0-9]+(.)/g, (_, character) => character.toUpperCase())
      .replace(/^[^a-zA-Z_]/, "_$&");
    groups[move.category].push({ key, value: `/assets/${move.category}/${path.basename(move.to)}` });
  }

  const lines = ["// Generated by scripts/organize-assets.mjs", "export const GENERATED_ASSETS = {"];
  for (const category of ["brand", "backgrounds", "icons"]) {
    lines.push(`  ${JSON.stringify(category)}: {`);
    for (const item of groups[category].sort((a, b) => a.key.localeCompare(b.key))) {
      lines.push(`    ${JSON.stringify(item.key)}: ${JSON.stringify(item.value)},`);
    }
    lines.push("  },");
  }
  lines.push("} as const;", "");

  if (apply) {
    fs.mkdirSync(path.dirname(registryPath), { recursive: true });
    fs.writeFileSync(registryPath, lines.join("\n"));
  }
}

if (!fs.existsSync(frontendRoot)) {
  throw new Error(`Frontend not found at ${path.relative(repoRoot, frontendRoot)}`);
}

const rootFiles = fs.readdirSync(repoRoot, { withFileTypes: true })
  .filter((entry) => entry.isFile() && VISUAL_EXTENSIONS.has(path.extname(entry.name).toLowerCase()))
  .map((entry) => path.join(repoRoot, entry.name));

const existingHashes = new Map();
if (fs.existsSync(publicAssetsRoot)) {
  for (const existingFile of walk(publicAssetsRoot)) {
    if (VISUAL_EXTENSIONS.has(path.extname(existingFile).toLowerCase())) {
      existingHashes.set(sha256(existingFile), existingFile);
    }
  }
}

const moves = [];
const duplicates = [];
for (const sourcePath of rootFiles) {
  const hash = sha256(sourcePath);
  const duplicatePath = existingHashes.get(hash);
  if (duplicatePath) {
    duplicates.push({ sourcePath, duplicatePath, hash });
    continue;
  }

  const category = classify(path.basename(sourcePath));
  const categoryDirectory = path.join(publicAssetsRoot, category);
  if (apply) fs.mkdirSync(categoryDirectory, { recursive: true });
  const destinationPath = uniqueDestination(categoryDirectory, path.basename(sourcePath));
  moves.push({ from: sourcePath, to: destinationPath, category, hash });
  existingHashes.set(hash, destinationPath);
}

if (apply) {
  for (const category of CATEGORIES) fs.mkdirSync(path.join(publicAssetsRoot, category), { recursive: true });
  for (const move of moves) fs.renameSync(move.from, move.to);
  for (const duplicate of duplicates) fs.rmSync(duplicate.sourcePath);
}

const changedReferenceFiles = replaceReferences(moves);
writeAssetRegistry(moves);

const counts = Object.fromEntries(CATEGORIES.map((category) => [category, 0]));
for (const move of moves) counts[move.category] += 1;

const report = [
  "# Asset Organisation Report",
  "",
  `Mode: **${apply ? "APPLIED" : "DRY RUN"}**`,
  `Root visual assets found: **${rootFiles.length}**`,
  `Files to move: **${moves.length}**`,
  `Confirmed duplicates: **${duplicates.length}**`,
  `Frontend text files requiring reference updates: **${changedReferenceFiles}**`,
  "",
  "## Destination counts",
  "",
  ...CATEGORIES.map((category) => `- ${category}: ${counts[category]}`),
  "",
  "## Moves",
  "",
  ...moves.map((move) => `- \`${path.relative(repoRoot, move.from)}\` → \`${path.relative(repoRoot, move.to)}\``),
  "",
  "## Confirmed duplicates",
  "",
  ...(duplicates.length
    ? duplicates.map((duplicate) => `- \`${path.relative(repoRoot, duplicate.sourcePath)}\` duplicates \`${path.relative(repoRoot, duplicate.duplicatePath)}\``)
    : ["- None"]),
  "",
];

if (apply) fs.writeFileSync(reportPath, report.join("\n"));
else process.stdout.write(`${report.join("\n")}\n`);

console.log(apply
  ? "Asset organisation applied. Review ASSET_ORGANISATION_REPORT.md, then run the frontend checks."
  : "Dry run complete. Re-run with --apply to move files and update references.");
