import {
  pgTable, serial, integer, text, boolean, real, timestamp, jsonb, unique,
} from "drizzle-orm/pg-core";
import { usersTable } from "./users";

export const aiModelRegistryTable = pgTable("ai_model_registry", {
  id: serial("id").primaryKey(),
  provider: text("provider").notNull(),
  model: text("model").notNull(),
  displayName: text("display_name").notNull(),
  inputCostPerMillionTokens: real("input_cost_per_million_tokens").notNull().default(0),
  outputCostPerMillionTokens: real("output_cost_per_million_tokens").notNull().default(0),
  contextWindow: integer("context_window").notNull().default(8192),
  latency: text("latency").notNull().default("medium"),
  qualityTier: text("quality_tier").notNull().default("standard"),
  capabilities: text("capabilities").array().notNull().default([]),
  enabled: boolean("enabled").notNull().default(true),
  notes: text("notes"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [unique("ai_model_registry_provider_model").on(t.provider, t.model)]);

export const aiUsageEventsTable = pgTable("ai_usage_events", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
  sessionId: integer("session_id"),
  projectId: text("project_id"),
  taskType: text("task_type").notNull().default("general"),
  executionMethod: text("execution_method").notNull().default("premium_model"),
  provider: text("provider"),
  model: text("model"),
  promptTokens: integer("prompt_tokens").notNull().default(0),
  completionTokens: integer("completion_tokens").notNull().default(0),
  totalTokens: integer("total_tokens").notNull().default(0),
  estimatedCostUsd: real("estimated_cost_usd").notNull().default(0),
  reportedCostUsd: real("reported_cost_usd"),
  estimatedCostWithoutOptimisation: real("estimated_cost_without_optimisation").notNull().default(0),
  estimatedSavingsUsd: real("estimated_savings_usd").notNull().default(0),
  savingsReasons: text("savings_reasons").array().notNull().default([]),
  durationMs: integer("duration_ms"),
  success: boolean("success").notNull().default(true),
  cacheHit: boolean("cache_hit").notNull().default(false),
  qualityMode: text("quality_mode").notNull().default("balanced"),
  tokensAvoided: integer("tokens_avoided").notNull().default(0),
  metadata: jsonb("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const aiOptimisationDecisionsTable = pgTable("ai_optimisation_decisions", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
  usageEventId: integer("usage_event_id"),
  taskType: text("task_type").notNull(),
  prompt: text("prompt").notNull().default(""),
  executionMethod: text("execution_method").notNull(),
  provider: text("provider"),
  model: text("model"),
  estimatedInputTokens: integer("estimated_input_tokens").notNull().default(0),
  estimatedOutputTokens: integer("estimated_output_tokens").notNull().default(0),
  estimatedCost: real("estimated_cost").notNull().default(0),
  estimatedCostWithoutViba: real("estimated_cost_without_viba").notNull().default(0),
  estimatedSavings: real("estimated_savings").notNull().default(0),
  savingsReasons: text("savings_reasons").array().notNull().default([]),
  confidence: real("confidence").notNull().default(0),
  qualityMode: text("quality_mode").notNull().default("balanced"),
  userApproved: boolean("user_approved"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const aiSavingsRecordsTable = pgTable("ai_savings_records", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
  periodStart: timestamp("period_start", { withTimezone: true }).notNull(),
  periodEnd: timestamp("period_end", { withTimezone: true }).notNull(),
  totalTasks: integer("total_tasks").notNull().default(0),
  tasksWithoutPremium: integer("tasks_without_premium").notNull().default(0),
  cacheHits: integer("cache_hits").notNull().default(0),
  localToolExecutions: integer("local_tool_executions").notNull().default(0),
  ruleEngineExecutions: integer("rule_engine_executions").notNull().default(0),
  economyModelExecutions: integer("economy_model_executions").notNull().default(0),
  premiumModelExecutions: integer("premium_model_executions").notNull().default(0),
  estimatedSpendUsd: real("estimated_spend_usd").notNull().default(0),
  estimatedSpendWithoutOptimisationUsd: real("estimated_spend_without_optimisation_usd").notNull().default(0),
  estimatedSavingsUsd: real("estimated_savings_usd").notNull().default(0),
  tokensAvoided: integer("tokens_avoided").notNull().default(0),
  duplicateTasksPrevented: integer("duplicate_tasks_prevented").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

export const aiTaskCacheTable = pgTable("ai_task_cache", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
  projectId: text("project_id"),
  taskFingerprint: text("task_fingerprint").notNull(),
  promptFingerprint: text("prompt_fingerprint").notNull(),
  taskType: text("task_type").notNull(),
  model: text("model").notNull(),
  provider: text("provider").notNull(),
  result: text("result").notNull(),
  resultMetadata: jsonb("result_metadata"),
  confidence: real("confidence").notNull().default(1),
  reuseCount: integer("reuse_count").notNull().default(0),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  invalidated: boolean("invalidated").notNull().default(false),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  lastUsedAt: timestamp("last_used_at", { withTimezone: true }).notNull().defaultNow(),
});

export const aiProjectMemoryTable = pgTable("ai_project_memory", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
  projectId: text("project_id").notNull(),
  memoryType: text("memory_type").notNull().default("general"),
  key: text("key").notNull(),
  value: text("value").notNull(),
  source: text("source").notNull().default("system"),
  confidence: real("confidence").notNull().default(1),
  userConfirmed: boolean("user_confirmed").notNull().default(false),
  pinned: boolean("pinned").notNull().default(false),
  outdated: boolean("outdated").notNull().default(false),
  version: integer("version").notNull().default(1),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const userAiBudgetsTable = pgTable("user_ai_budgets", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }).unique(),
  monthlyBudgetUsd: real("monthly_budget_usd"),
  warnThresholdUsd: real("warn_threshold_usd"),
  hardLimitUsd: real("hard_limit_usd"),
  premiumApprovalThresholdUsd: real("premium_approval_threshold_usd").notNull().default(0.25),
  requireApprovalAboveUsd: real("require_approval_above_usd").notNull().default(1.0),
  autoEconomyAtPercent: real("auto_economy_at_percent").notNull().default(80),
  blockPremiumAtLimit: boolean("block_premium_at_limit").notNull().default(true),
  allowMultiModel: boolean("allow_multi_model").notNull().default(false),
  qualityMode: text("quality_mode").notNull().default("balanced"),
  useExistingFirst: boolean("use_existing_first").notNull().default(true),
  providerLimits: jsonb("provider_limits"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const userAiSubscriptionsTable = pgTable("user_ai_subscriptions", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
  provider: text("provider").notNull(),
  displayName: text("display_name").notNull(),
  monthlyCostUsd: real("monthly_cost_usd").notNull().default(0),
  includedUsageDescription: text("included_usage_description"),
  renewalDay: integer("renewal_day"),
  prioritise: boolean("prioritise").notNull().default(false),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (t) => [unique("user_ai_subscriptions_user_provider").on(t.userId, t.provider)]);
