import { pgTable, serial, text, integer, timestamp, boolean, jsonb } from "drizzle-orm/pg-core";

export const contentCreatorCampaigns = pgTable("content_creator_campaigns", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  objective: text("objective"),
  targetAudience: text("target_audience"),
  platforms: jsonb("platforms").$type<string[]>().default([]),
  seoKeywords: jsonb("seo_keywords").$type<string[]>().default([]),
  brandVoice: text("brand_voice"),
  aiStrategy: text("ai_strategy"),
  status: text("status").notNull().default("draft"),
  totalPieces: integer("total_pieces").default(0),
  publishedPieces: integer("published_pieces").default(0),
  tiktokLinked: boolean("tiktok_linked").default(false),
  seoLinked: boolean("seo_linked").default(true),
  advertisingLinked: boolean("advertising_linked").default(false),
  startDate: timestamp("start_date"),
  endDate: timestamp("end_date"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const contentCreatorPieces = pgTable("content_creator_pieces", {
  id: serial("id").primaryKey(),
  campaignId: integer("campaign_id"),
  platform: text("platform").notNull(),
  contentType: text("content_type").notNull(),
  title: text("title"),
  headline: text("headline"),
  body: text("body"),
  callToAction: text("call_to_action"),
  hashtags: jsonb("hashtags").$type<string[]>().default([]),
  hook: text("hook"),
  videoScript: text("video_script"),
  visualDirections: text("visual_directions"),
  seoKeywords: jsonb("seo_keywords").$type<string[]>().default([]),
  imagePrompt: text("image_prompt"),
  mediaUrl: text("media_url"),
  seoScore: integer("seo_score").default(0),
  qualityScore: integer("quality_score").default(0),
  status: text("status").notNull().default("draft"),
  aiPrompt: text("ai_prompt"),
  aiModel: text("ai_model"),
  generationMs: integer("generation_ms"),
  publishedAt: timestamp("published_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const contentCreatorSchedules = pgTable("content_creator_schedules", {
  id: serial("id").primaryKey(),
  pieceId: integer("piece_id").notNull(),
  campaignId: integer("campaign_id"),
  platform: text("platform").notNull(),
  scheduledAt: timestamp("scheduled_at").notNull(),
  status: text("status").notNull().default("pending"),
  publishedAt: timestamp("published_at"),
  error: text("error"),
  createdAt: timestamp("created_at").defaultNow(),
});

export const contentCreatorAnalytics = pgTable("content_creator_analytics", {
  id: serial("id").primaryKey(),
  pieceId: integer("piece_id").notNull(),
  campaignId: integer("campaign_id"),
  platform: text("platform").notNull(),
  impressions: integer("impressions").default(0),
  likes: integer("likes").default(0),
  comments: integer("comments").default(0),
  shares: integer("shares").default(0),
  clicks: integer("clicks").default(0),
  engagementRate: text("engagement_rate").default("0"),
  recordedAt: timestamp("recorded_at").defaultNow(),
  createdAt: timestamp("created_at").defaultNow(),
});
