import {
  pgTable,
  serial,
  integer,
  text,
  timestamp,
  boolean,
  jsonb,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";
import { usersTable } from "./users";

export const marketplaceSellersTable = pgTable("marketplace_sellers", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => usersTable.id, { onDelete: "set null" }),
  slug: text("slug").notNull(),
  displayName: text("display_name").notNull(),
  bio: text("bio"),
  avatarUrl: text("avatar_url"),
  isPlatformBot: boolean("is_platform_bot").notNull().default(false),
  botKey: text("bot_key"),
  botEnabled: boolean("bot_enabled").notNull().default(true),
  verified: boolean("verified").notNull().default(false),
  status: text("status").notNull().default("active"),
  stripeConnectAccountId: text("stripe_connect_account_id"),
  stripeConnectOnboarded: boolean("stripe_connect_onboarded").notNull().default(false),
  totalSales: integer("total_sales").notNull().default(0),
  totalRevenueCents: integer("total_revenue_cents").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  slugUnique: uniqueIndex("marketplace_sellers_slug_unique").on(table.slug),
  botKeyUnique: uniqueIndex("marketplace_sellers_bot_key_unique").on(table.botKey),
  userIdx: index("marketplace_sellers_user_idx").on(table.userId),
}));

export const marketplaceModulesTable = pgTable("marketplace_modules", {
  id: serial("id").primaryKey(),
  sellerId: integer("seller_id").notNull().references(() => marketplaceSellersTable.id, { onDelete: "restrict" }),
  slug: text("slug").notNull(),
  name: text("name").notNull(),
  shortDescription: text("short_description").notNull(),
  description: text("description"),
  category: text("category").notNull().default("module"),
  tags: text("tags").array().notNull().default([]),
  language: text("language"),
  framework: text("framework"),
  version: text("version").notNull().default("1.0.0"),
  license: text("license").notNull().default("commercial"),
  priceCents: integer("price_cents").notNull().default(0),
  currency: text("currency").notNull().default("usd"),
  status: text("status").notNull().default("draft"),
  verificationStatus: text("verification_status").notNull().default("pending"),
  verificationReport: jsonb("verification_report"),
  manifest: jsonb("manifest").notNull().default({}),
  compatibility: jsonb("compatibility").notNull().default({}),
  requirements: jsonb("requirements").notNull().default({}),
  storageKey: text("storage_key"),
  downloadUrl: text("download_url"),
  fileName: text("file_name"),
  fileSizeBytes: integer("file_size_bytes"),
  fileHashSha256: text("file_hash_sha256"),
  previewImageUrl: text("preview_image_url"),
  demoUrl: text("demo_url"),
  featured: boolean("featured").notNull().default(false),
  generatedByViba: boolean("generated_by_viba").notNull().default(false),
  sourceBuildId: text("source_build_id"),
  totalSales: integer("total_sales").notNull().default(0),
  totalDownloads: integer("total_downloads").notNull().default(0),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  slugUnique: uniqueIndex("marketplace_modules_slug_unique").on(table.slug),
  sellerIdx: index("marketplace_modules_seller_idx").on(table.sellerId),
  statusIdx: index("marketplace_modules_status_idx").on(table.status),
  hashIdx: index("marketplace_modules_hash_idx").on(table.fileHashSha256),
}));

export const marketplacePurchasesTable = pgTable("marketplace_purchases", {
  id: serial("id").primaryKey(),
  buyerUserId: integer("buyer_user_id").notNull().references(() => usersTable.id, { onDelete: "restrict" }),
  moduleId: integer("module_id").notNull().references(() => marketplaceModulesTable.id, { onDelete: "restrict" }),
  sellerId: integer("seller_id").notNull().references(() => marketplaceSellersTable.id, { onDelete: "restrict" }),
  stripeCheckoutSessionId: text("stripe_checkout_session_id"),
  stripePaymentIntentId: text("stripe_payment_intent_id"),
  amountCents: integer("amount_cents").notNull(),
  currency: text("currency").notNull().default("usd"),
  platformFeeCents: integer("platform_fee_cents").notNull().default(0),
  sellerNetCents: integer("seller_net_cents").notNull().default(0),
  status: text("status").notNull().default("pending"),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  checkoutUnique: uniqueIndex("marketplace_purchases_checkout_unique").on(table.stripeCheckoutSessionId),
  buyerIdx: index("marketplace_purchases_buyer_idx").on(table.buyerUserId),
}));

export const userModuleInventoryTable = pgTable("user_module_inventory", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => usersTable.id, { onDelete: "cascade" }),
  moduleId: integer("module_id").notNull().references(() => marketplaceModulesTable.id, { onDelete: "restrict" }),
  purchaseId: integer("purchase_id").references(() => marketplacePurchasesTable.id, { onDelete: "set null" }),
  acquiredVia: text("acquired_via").notNull().default("purchase"),
  licenseSnapshot: jsonb("license_snapshot").notNull().default({}),
  versionOwned: text("version_owned").notNull().default("1.0.0"),
  downloadCount: integer("download_count").notNull().default(0),
  lastDownloadedAt: timestamp("last_downloaded_at", { withTimezone: true }),
  addedAt: timestamp("added_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  ownershipUnique: uniqueIndex("user_module_inventory_ownership_unique").on(table.userId, table.moduleId),
  userIdx: index("user_module_inventory_user_idx").on(table.userId),
}));

export const marketplaceBotRunsTable = pgTable("marketplace_bot_runs", {
  id: serial("id").primaryKey(),
  sellerId: integer("seller_id").notNull().references(() => marketplaceSellersTable.id, { onDelete: "cascade" }),
  runType: text("run_type").notNull(),
  status: text("status").notNull().default("running"),
  modulesCreated: integer("modules_created").notNull().default(0),
  error: text("error"),
  report: jsonb("report").notNull().default({}),
  startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
  finishedAt: timestamp("finished_at", { withTimezone: true }),
});
